from Problem_6 import solution1

def test_simple_cases():
    assert solution1("aaaa") == 1
    assert solution1("ab") == 2
    assert solution1("abc") == 3
    assert solution1("kcwa") == 4
    assert solution1("ezxpedrz") == 8
    assert solution1("fgluxhtza") == 9
    assert solution1("mjoaexpfz") == 9
    assert solution1("linyxx") == 6
    assert solution1("pay") == 3
    assert solution1("rxmc") == 4
    assert solution1("qkkjahy") == 7
    assert solution1("slcswzxu") == 8
    assert solution1("zoiy") == 4
    assert solution1("rhjaux") == 6
    assert solution1("fkjfimi") == 7
    assert solution1("pbkflfnd") == 8
    assert solution1("rthqixv") == 7
    assert solution1("rej") == 3
    assert solution1("ifhbywu") == 7
    assert solution1("oost") == 4
    assert solution1("nxwjjwsas") == 9
    assert solution1("moockefg") == 8
    assert solution1("qqydevz") == 7
    assert solution1("wwivmp") == 6
    assert solution1("togvvenfp") == 9
    assert solution1("oolvpej") == 7
    assert solution1("tzegpv") == 6
    assert solution1("beahzutke") == 9
    assert solution1("xzwepkip") == 8
    assert solution1("sis") == 3
    assert solution1("qtbflguk") == 8
    assert solution1("jam") == 3
    assert solution1("gqbzuvv") == 7
    assert solution1("abvgipdym") == 9
    assert solution1("ttff") == 4
    assert solution1("jjeu") == 4
    assert solution1("rphw") == 4
    assert solution1("nbgwgz") == 6
    assert solution1("setbdn") == 6
    assert solution1("pscwbl") == 6
    assert solution1("flgboo") == 6
    assert solution1("bfxpdk") == 6
    assert solution1("mofei") == 5
    assert solution1("qyr") == 3
    assert solution1("uxk") == 3
    assert solution1("nbmy") == 4
    assert solution1("ege") == 3
    assert solution1("usoriq") == 6
    assert solution1("wjuwlt") == 6
    assert solution1("bnodui") == 6
    assert solution1("aevvqf") == 6
    assert solution1("iaktug") == 6
    assert solution1("vhufs") == 5
    assert solution1("hiat") == 4
    assert solution1("mzaym") == 5
    assert solution1("xnlqu") == 5
    assert solution1("zqdb") == 4
    assert solution1("flq") == 3
    assert solution1("oar") == 3
    assert solution1("fezfrb") == 6
    assert solution1("ipszr") == 5
    assert solution1("edyr") == 4
    assert solution1("nve") == 3
    assert solution1("yti") == 3
    assert solution1("bmfvr") == 5
    assert solution1("psafv") == 5
    assert solution1("zlhtd") == 5
    assert solution1("pacp") == 4
    assert solution1("qhgsk") == 5
    assert solution1("eyde") == 4
    assert solution1("eyv") == 3
    assert solution1("dxbgtvxq") == 8
    assert solution1("mfdx") == 4
    assert solution1("xask") == 4
    assert solution1("qddp") == 4
    assert solution1("oas") == 3
    assert solution1("fjilakl") == 7
    assert solution1("xwdsk") == 5
    assert solution1("owqgr") == 5
    assert solution1("lxv") == 3
    assert solution1("bxbb") == 4
    assert solution1("jbfisms") == 7
    assert solution1("zqupo") == 5
    assert solution1("qye") == 3
    assert solution1("hhxosqlg") == 8
    assert solution1("zhb") == 3
    assert solution1("iwkj") == 4
    assert solution1("maen") == 4
    assert solution1("lsliyhze") == 8
    assert solution1("doocsri") == 7
    assert solution1("cjc") == 3
    assert solution1("avi") == 3
    assert solution1("rfit") == 4
    assert solution1("tlgffvv") == 7
    assert solution1("vlk") == 3
    assert solution1("ljeftwkpr") == 9
    assert solution1("itzso") == 5
    assert solution1("zxfscko") == 7
    assert solution1("ewzfvb") == 6
    assert solution1("wdk") == 3
    assert solution1("gmlivxfm") == 8
    assert solution1("yvsnt") == 5